### ISSUE TITLE
Size mismtach for pre-trained model

### ISSUE THREAD

**Issue by babar41** [yuyanli0831/OmniFusion#3]
Hi, Thank you very much for sharing the source code and the pre-trained models. 

I am trying to run the evaluation on your provided pre-trained models for Stanford2D3D. However, while loading the .pth file, torch gives the following size mismatch error. It appears the down1 layer may have been modified after the training file was saved. Could you please advise how to resolve it ?

Traceback (most recent call last):
  File "test.py", line 110, in <module>
    network.load_state_dict(ckpt)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.down1.weight: copying a param with shape torch.Size([8, 512, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 512, 1, 1, 1]).
	size mismatch for module.down1.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([32]).

**Comment by yuyanli0831** [comment]
This is caused by different training/testing patch size settings. You can modify it by changing the output channel size from 32 to 8 accordingly.

**Comment by jiayaozhang** [comment]
Would you mind telling more specific and how to change output channel size from 32 to 8 ?

I try to change the patchsize but didn't work 

Also I have tried like this `ckpt.pop("module.down1")`, also not make it work

**Comment by jiayaozhang** [comment]
Now I solve the mismatch problem after below codes
```
# parallel on multi gpu
network = nn.DataParallel(network)

ckpt = torch.load(args.save_path + '/checkpoints/checkpoint_best.pth')
# for k,v in ckpt.items():
    # print(k)
ckpt.pop("module.down1.weight")
ckpt.pop("module.down1.bias")


network_dict = network.state_dict()
# print(network)
# ckpt = {k:v for k, v in ckpt.items() if k in network and 'module.down1' not in k}
ckpt = {k:v for k, v in ckpt.items() if k in network_dict}



network_dict.update(ckpt)

network.load_state_dict(network_dict)
network.cuda()

```

But I encounter different error

Can you help to solve this?

 ```
 File "/home/user/chihan/OmniFusion_Jiayao/dataset_loader_stanford.py", line 53, in __getitem__
    depth = self.readDepthPano(self.root_path + relative_paths[1])
  File "/home/user/chihan/OmniFusion_Jiayao/dataset_loader_stanford.py", line 108, in readDepthPano
    depth = cv2.imread(path, -1).astype(np.float32)
AttributeError: 'NoneType' object has no attribute 'astype'

```

Many thanks!

**Comment by babar414** [comment]
This error is probably caused by the 'path' to depth image not correct, therefore it is not able to find the image using cv2.imread so it returns 'None'. Make sure you provide correct paths and filenames for depths and rgbs in the filenames txt file. Guessing from your code, you maybe using "filenames/test_stanford2d3d.txt" so you need to check that file.

**Comment by jiayaozhang** [comment]
Thanks! I use one image for train and test, but the batchsize is 2 so i add more images into the test_stanford2d3d.txt then it works!

And for the size mismatch problem, I also found that we can direct modify here and made it work! In spherical_model_iterative.py line 274 and line 275

       #self.down2 = nn.Conv3d(512, 512//64, kernel_size=1, stride=1, padding=0)
       self.transformer = Transformer_cascade(512, npatches, depth=6, num_heads=4)

**Comment by apple2373** [comment]
I had the same issue, and solved by changing this line 

https://github.com/yuyanli0831/OmniFusion/blob/bdc621b9e08089e1e13b6d9006bf356893cf3b6c/model/spherical_model_iterative.py#L274
to 
`self.down1 = nn.Conv3d(512, 8, kernel_size=1, stride=1, padding=0)`

**Comment by apple2373** [comment]
well, I also had to do the similar change for the training. 

Change this line 
https://github.com/yuyanli0831/OmniFusion/blob/bdc621b9e08089e1e13b6d9006bf356893cf3b6c/model/spherical_model.py#L211
to 
`self.down = nn.Conv3d(512, 8, kernel_size=1, stride=1, padding=0)`
